version : '3.7'

services:
   lop-api:
      image: docker.pkg.github.com/spydx/dat251gr9/lop-api-dev:backend
      #build: 
      #   context: lop-backend
      #   dockerfile: Dockerfile
      healthcheck:
         test: curl --fail -s http://localhost:8080/ || exit 1
         timeout: 45s
         interval: 10s
         retries: 10
      ports:
         - 8080:8080
      environment:
         SPRING_DATASOURCE_URL: jdbc:mariadb://lop-db:3306/lopdb?createDatabaseIfNotExist=true
      depends_on:
         - lop-db
      #restart: always
      networks:
         - backend
         - frontend
   lop-db:
      image: mariadb:latest
      environment:
         MYSQL_DATABASE: lopdb
         MYSQL_ROOT_PASSWORD: password
      volumes:
         - db-data:/var/lib/mysql
      ports:
         - 3306:3306
      networks:
         - backend



volumes:
   db-data:
   
networks:
   backend:
   frontend: 