version : '3.7'

services:
   cypress:
      image: "cypress/included:6.8.0"
      depends_on:
         - lop-frontend
      environment:
         - CYPRESS_baseUrl=http://lop-frontend/
      working_dir: /e2e
      volumes:
         - ./e2e:/e2e/

   lop-frontend:
      build:
         context: lop-frontend
         dockerfile: Dockerfile
         args:
            REACT_APP_BACKEND_ENDPOINT: http://react-auth-backend:8080/api
      ports:
         - 80:80
      depends_on:
         - lop-api


   lop-api:
      image: docker.pkg.github.com/spydx/dat251gr9/lop-api-dev:backend
      #build: 
      #   context: lop-backend
      #   dockerfile: Dockerfile
      healthcheck:
         test: curl --fail -s http://localhost:8080/ || exit 1
         timeout: 45s
         interval: 10s
         retries: 10
      ports:
         - 8080:8080
      environment:
         SPRING_DATASOURCE_URL: jdbc:mariadb://lop-db:3306/lopdb?createDatabaseIfNotExist=true
      depends_on:
         - lop-db

   lop-db:
      image: mariadb:latest
      environment:
         MYSQL_DATABASE: lopdb
         MYSQL_ROOT_PASSWORD: password
      volumes:
         - db-data:/var/lib/mysql
      ports:
         - 3306:3306

volumes:
   db-data: